### ISSUE TITLE
Build dir not set when using cmake 0.1 as per docs

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [rust-lang/cmake-rs#126]
I had some trouble getting things to work with cmake 0.1 which - contrary to the current version - does not set the working dir before the final build step.
Upgrading to 0.1.42 seems to have resolved my build problem. I would suggest upgrading the documentation to point to this working version as well so as to save people some time hunting down an issue that's already resolved.

**Comment by aelray** [comment]
I have the same issue, tried various versions including 0.1.42 and latest (currently 0.1.49)
```
  -- Build files have been written to: /some/path/application-360c69553e2a07e8/out
  running: "cmake" "--build" "." "--target" "MY_TARGET" "--config" "Debug" "--parallel" "16"

  --- stderr
  Error: could not load cache
```
