### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cmake-rs#127]
I've maintained this crate for quite some time now, but I don't think I really have the time/energy to maintain this any more. I personally only ever really barely understood CMake to begin with so I was also probably never the best maintainer of this crate either. 

At this point, I'd be interested in finding someone else to take over ownership of this crate. Given a suitable maintainer I'd be happy to transfer the repository and crates.io crate as well.

This crate is pretty heavily depended on in the crate ecosystem, however, so I would prefer to not simply hand this over to the first volunteer. I would ideally prefer to hand it off to someone who's otherwise been involved in the Rust community for some time and I can trust to keep the crate well-maintained and suitable for the number of crates that depend on this crate.

**Comment by Dushistov** [comment]
May be re-post this message also on reddit/users.rust-lang.org ?

**Comment by PsiACE** [comment]
I am willing to participate in the maintenance work.

**Comment by strega-nil-ms** [comment]
I'm not super invested in the Rust community anymore, but I am heavily invested into CMake (and am probably one of the more expert people in it, given my work in vcpkg); I don't know if I would be best as a primary maintainer, but I'd love to help.

**Comment by strega-nil** [comment]
I'm not super invested in the Rust community anymore, but I am heavily invested into CMake (and am probably one of the more expert people in it, given my work in vcpkg); I don't know if I would be best as a primary maintainer, but I'd love to help.

**Comment by alexcrichton** [comment]
Ok I've added @strega-nil to this repository for now and sorry @PsiACE I don't recognize you but if you're willing please feel free to help out reviewing PRs and triaging things, it would be greatly appreciated! If it goes well I'd be happy to add you too.

**Comment by aloucks** [comment]
Hi @alexcrichton, I can try to help with maintaining this crate if you're open to it. I'm not a heavy cmake user, but I do have some projects that leverage this and I'd like to make sure they continue to compile.

**Comment by mygnu** [comment]
Hey, I also depend upon this crate for work, happy to help with maintenance.

**Comment by aloucks** [comment]
> To clarify I'm not necessarily looking for assistance in maintainership any more, I'm more looking now to completely transfer this repository to a new owner.

That's understandable. @m-ou-se [suggested migrating `cc-rs` into the `rust-lang` org](https://github.com/alexcrichton/cc-rs/issues/663#issuecomment-1063212424). Ideally `cmake-rs` could be migrated as well. If that's not desirable (or may take a while), perhaps a new org could be created to host both `cc-rs` and `cmake-rs` (e.g. `rust-native-build-tools`)?

**Comment by the-Arioch** [comment]
This issue seems ot be hidden deep and hard to find.

It seems to me such a state of the crate has ot be announced at least at the top of the 'front page' [README.md](https://github.com/alexcrichton/cmake-rs/blob/master/README.md) - so would be easily visible. And consequently on https://crates.io/crates/cmake description.

Perhaps even be printed aout as a warning message during any work of the crate - this crate is now subject to bit-rot, thus it seems ot be fare to announce it during work, for all the projects that "merely use" it for years, so they would know.

----

Maybe this person/team has experience with BOTH CMake and Rust?
https://crates.io/crates/cmake-version-manager

**Comment by m-ou-se** [comment]
https://github.com/alexcrichton/cc-rs/issues/663#issuecomment-1120180602:

> We've discussed this in the Rust library team meeting this week, and we think it's best if `cc` and `cmake` are both moved to the `rust-lang` organisation. Currently, we won't have the bandwith to work on new features to these crates, but we will be able to review incoming PRs and make sure these crates stay maintained.
>
> @alexcrichton If you're on board with this, can you transfer the repos to the `rust-lang` GitHub organisation, and invite `@rust-lang-owner` as owner to the crates on crates.io?

**Comment by thomcc** [comment]
This is now under the maintainership of the rust-lang/crates-maintainers team. I am not a cmake expert, but I'm familiar enough with the tool to know how it works and help keep this maintained.

I'm going to close this because there's nothing really left to do here.
