### ISSUE TITLE
0.1.46 does not work

### ISSUE THREAD

**Issue by fafhrd91** [rust-lang/cmake-rs#131]
trying to build snmalloc-rs crate and getting `Unknown argument --parallel` error. works fine with 0.1.45

**Comment by mjp41** [comment]
@fafhrd91 which version of CMake are you using.  I looks like this release picked up a requirement on 3.12.
https://github.com/alexcrichton/cmake-rs/pull/123/files

That PR says `--parallel` was introduced with v3.12.
https://cmake.org/cmake/help/v3.12/manual/cmake.1.html#build-tool-mode

The current release of snmalloc-rs only requires 3.8, so perhaps the checking is missing from cmake-rs for the new minimum version?

**Comment by mgattozzi** [comment]
I'm trying to see if there's a way to bump us to to 3.12 at work but I'm not sure if that's possible right now and still working on that. The patch update is affecting libz-sys which isn't using a pinned version of this and so cargo update broke the build.

**Comment by mygnu** [comment]
related https://github.com/alexcrichton/cmake-rs/issues/131

**Comment by strega-nil** [comment]
I can try to take a look at this later today; it would make sense to me to do version checks, which should be pretty easy given the current code? Especially since `--parallel` is not necessarily a _need_.

**Comment by rwthompsonii** [comment]
Is there any way to just _check_ the version of `cmake` by issuing a "--version" command, prior to using flags that aren't present?  This bit me hard today.

**Comment by taiki-e** [comment]
Filed #146 to fix this.
