### ISSUE TITLE
Support for passing to CMake any random string

### ISSUE THREAD

**Issue by lilianmoraru** [rust-lang/cmake-rs#27]
Currently, the crate limits the user on what kind of options he can pass to `CMake`.
I am trying to pass `-C path/to/a/cmake/script.cmake`(it's a script that speeds-up build-times, I use it for all cmake projects) and it is just impossible to do that with the current API.
I think there should be an option where the user can pass flags himself, whatever he wants.

**Comment by alexcrichton** [comment]
Seems reasonable to me! Would you be interested in sending a PR?

**Comment by lilianmoraru** [comment]
I could do that.
What do you think would be the appropriate naming for these functions?
I am thinking(inspired by `std::process::Command`) of: `cmake_arg/cmake_args` or `arg/args`?
At least for me, `arg/args` seems too ambiguous.

**Comment by alexcrichton** [comment]
Yeah `cmake_arg` and `cmake_args` sounds good to me!

**Comment by tomjakubowski** [comment]
I think this use-case is covered by either `configure_arg()` or `build_arg()`, where configure_arg() passes arguments before the `--` and `build_arg()` passes arguments after, like so:

```
cmake <configure_arg1> <configure_arg2> ... -- <build_arg1> <build_arg2>...
```

**Comment by lilianmoraru** [comment]
Very nice of me suggesting I am committing to implement it and then not doing it.
